### ISSUE TITLE
代码中几个常量的含义

### ISSUE THREAD

**Issue by xrui94** [yueyan-zm/shp_to_3dtiles#1]
请教一下，这几个常量是什么意思？它们是怎么计算得来的？
![image](https://user-images.githubusercontent.com/29156275/230873202-cd498c09-c086-498b-9df4-7f7fd82bdbd0.png)
![image](https://user-images.githubusercontent.com/29156275/230873286-413e18f8-04a9-4701-8515-c3a5f955a5fc.png)

**Comment by yueyan-zm** [comment]
下面那几个比较大的是地球椭球参数，百度分别搜索：WGS84椭球参数 和 大地坐标系、地固坐标系，上面那个两个应该是经纬度和米之间的计算常数，大家都这么用的，我这个参考的3dtiles就是这样写的，我也只是用rust重写了一次而已
